### ISSUE TITLE
zpool import not working. Hence unable to make zdb work.

### ISSUE THREAD

**Issue by datacore-skumar** [openzfsonwindows/openzfs#14]
I am trying to make zdb work by porting changes from ZFSin.
Looks like zpool import is broken on Windows.
@lundman Is this a known issue? and are you working on it? 
```
Z:\openzfs\out\install\x64-Debug-2\bin>zpool export tank1
zunmount(tank1,E:\ ) running
zunmount(tank1,E:\ ) returns 0

Z:\openzfs\out\install\x64-Debug-2\bin>zpool status
no pools available

Z:\openzfs\out\install\x64-Debug-2\bin>zpool import tank1
path '\\?\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&020000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive1'
read partitions ok 0
asking libefi to read label
EFI read OK, max partitions 9
    part 0:  offset 800:    len 63fb000:    tag: 4    name: 'zfs-0000506a00004abb'
    part 8:  offset 63fb800:    len 4000:    tag: b    name: ''
path '\\?\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive0'
read partitions ok 4
    mbr 0: type 7 off 0x100000 len 0x22500000
    mbr 1: type 7 off 0x22600000 len 0xc5d900000
    mbr 2: type 0 off 0x0 len 0x0
    mbr 3: type 0 off 0x0 len 0x0
asking libefi to read label
path '\\?\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&030000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive2'
read partitions ok 2
    gpt 0: type 5872d3c0 off 0x100000 len 0xc7f600000
    gpt 1: type 5872d3c0 off 0xc7f700000 len 0x800000
asking libefi to read label
EFI read OK, max partitions 9
    part 0:  offset 800:    len 63fb000:    tag: 4    name: 'zfs-00000f17000073da'
    part 8:  offset 63fb800:    len 4000:    tag: b    name: ''
Processing volume '\\?\Volume{9bb5203f-0000-0000-0000-100000000000}'
Processing volume '\\?\Volume{9bb5203f-0000-0000-0000-602200000000}'
Processing volume '\\?\Volume{be19aaed-3fd1-11eb-9067-806e6f6e6963}'
working on dev '#1048576#53676605440#\\?\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&020000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
setting path here '/dev/physicaldrive1'
setting physpath here '#1048576#53676605440#\\?\scsi#disk&ven_vbox&prod_harddisk#4&2617aeae&0&020000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
cannot import 'tank1': one or more devices is currently unavailable

Z:\openzfs\out\install\x64-Debug-2\bin>zpool status
no pools available

```

**Comment by lundman** [comment]
I actually thought it was working, unless you found a cornercase. One thing that could be worth checking, is "offline" of disks, there was an issue where we left disks offline after export. Flipping them Online in diskmanager would fix it.

**Comment by datacore-skumar** [comment]
Thanks for the prompt response!
We are not seeing any disk being made offline after creating zpool, as we are not creating any zvol.
Simple zpool export and then import is failing. So there is no zvol, no IO.

FYI
For a zpool named tank2
```
Z:\openzfs\out\install\x64-Debug-2\bin>zdb
```
Output:
```
tank2:
    version: 5000
    name: 'tank2'
    state: 0
    txg: 4
    pool_guid: 70254533809252557
    errata: 0
    hostid: 2013764521
    hostname: 'Windows'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 70254533809252557
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 2443401389210331043
            path: '/dev/physicaldrive1'
            phys_path: '#1048576#53676605440#\\?\PHYSICALDRIVE1'
            whole_disk: 1
            metaslab_array: 259
            metaslab_shift: 29
            ashift: 12
            asize: 53671886848
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 257
            com.delphix:vdev_zap_top: 258
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
For zdb properties like :
```
zdb -D tank2
zdb -h tank2
zdb -c tank2 
```
It has same output : 
```
zdb: can't open 'tank2': No such device or address
```
