### ISSUE TITLE
/dev/zfs and /proc/self/mounts are required.

### ISSUE THREAD

**Issue by meiotik** [openzfsonwindows/openzfs#76]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Windows 10
Distribution Version	|21H1
Kernel Version	|OS Build 19043.1165
Architecture	|amd64
OpenZFS Version	|[2022/02/21 Rebase, +zstd](https://www.lundman.net/OpenZFSOnWindows-debug-2.1.99-968-g32152cd8a-dirty.exe)

```
C:\>zfs.exe --version
zfs-2.0.0-2
zfs-kmod-(registry lookup failed)

C:\>
```
### Describe the problem you're observing
`zfs.exe` and `zpool.exe` looking for /dev and /proc.
### Describe how to reproduce the problem
```
C:\>zpool.exe import -a
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

C:\>zpool.exe status
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

C:\>zfs.exe list
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

C:\>
```
### `zdb.exe` can see still see the pool.
```
C:\>zdb.exe
crystal:
    version: 5000
    name: 'crystal'
    state: 0
    txg: 733936
    pool_guid: 8438582862880170364
    errata: 0
    hostid: 6277814
    hostname: 'Windows'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 8438582862880170364
        create_txg: 4
        children[0]:
            type: 'raidz'
            id: 0
            guid: 3172860730755905535
            nparity: 2
            metaslab_array: 138
            metaslab_shift: 34
            ashift: 12
            asize: 32006175981568
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 129
            children[0]:
                type: 'disk'
                id: 0
                guid: 8328723666407286888
                path: '/dev/physicaldrive0'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE0'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 130
            children[1]:
                type: 'disk'
                id: 1
                guid: 5445821570346932139
                path: '/dev/physicaldrive1'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE1'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 131
            children[2]:
                type: 'disk'
                id: 2
                guid: 16884514173996848
                path: '/dev/physicaldrive2'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE2'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 132
            children[3]:
                type: 'disk'
                id: 3
                guid: 5384160299251805283
                path: '/dev/physicaldrive3'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE3'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 133
            children[4]:
                type: 'disk'
                id: 4
                guid: 624237522323206110
                path: '/dev/physicaldrive4'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE4'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 134
            children[5]:
                type: 'disk'
                id: 5
                guid: 4588928636543824743
                path: '/dev/physicaldrive5'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE5'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 135
            children[6]:
                type: 'disk'
                id: 6
                guid: 972731525412172133
                path: '/dev/physicaldrive6'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE6'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 136
            children[7]:
                type: 'disk'
                id: 7
                guid: 2551185826356630758
                path: '/dev/physicaldrive7'
                phys_path: '#1048576#4000776716288#\\?\PHYSICALDRIVE7'
                whole_disk: 1
                create_txg: 4
                com.delphix:vdev_zap_leaf: 137
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

C:\>
```
